language: node_js
sudo: false
dist: trusty

node_js:
  - "node"

env:
  - CXX=g++-4.8 HUGO_VERSION=0.26


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

notifications:
  webhooks:
    urls:
      - https://discordapp.com/api/webhooks/347631273948479491/4wGTEwmPgA4AfTiHdIty2qszWdtNRve8LxRzfZqlgbIrbf7BSrJqg5zAa-szACKQSdD_
    on_success: change # default: always
    on_failure: always # default: always
    on_start: change   # default: never
    on_cancel: always # default: always
    on_error: always # default: always

cache:
  directories:
    - "node_modules"

before_install:
  - npm i -g npm

install:
  - npm install
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar -xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - chmod +x hugo

before_script:
  - npm install -g gulp-cli
  - mkdir binaries && mv hugo binaries/
  - export PATH=$PATH:$PWD/binaries/

script:
  - gulp build
