baseURL = "https://csec.infosecgur.us"
languageCode = "fr-FR"
title = "Le Comptoir Sécu"
MetaDataFormat = "yaml"
DefaultContentLanguage = "fr"
copyright = "2017 Le Comptoir Sécu"
[permalinks]
podcast = "/podcast/:title/"
sechebdo = "/sechebdo/:title/"
annonce = "/annonce/:title/"
article = "/article/:title/"
video = "/video/:title/"
paginate = 10

[menu]
  [[menu.left]]
      name= "Blog"
      pre = "fa-pencil"
      weight = 20
      identifier = "blog"
      url = "/article/"
      [[menu.left]]
          name= "Annonces"
          parent = "blog"
          weight = 21
          identifier = "annonce"
          url = "/annonce/"
      [[menu.left]]
          name= "Articles"
          parent = "blog"
          weight = 22
          identifier = "article"
          url = "/article/"
  [[menu.left]]
      name = "Podcasts"
      pre = "fa-microphone"
      weight = 30
      identifier = "podcast"
      url = "/podcast/"
      [[menu.left]]
          name = "Émissions"
          parent = "podcast"
          weight = 31
          identifier = "emission"
          url = "/categories/emission/"
      [[menu.left]]
          name = "Hors Séries"
          parent = "podcast"
          weight = 32
          identifier = "hors-serie"
          url = "/categories/hors-serie/"
  [[menu.left]]
      name= "Vidéos"
      pre = "fa-video-camera"
      weight = 40
      identifier = "video"
      url = "/video/"
      [[menu.left]]
          name= "SECompris"
          parent = "video"
          weight = 41
          identifier = "secompris"
          url = "/categories/secompris/"
      [[menu.left]]
          name= "SEClair"
          parent = "video"
          weight = 42
          identifier = "seclair"
          url = "/categories/seclair/"
      [[menu.left]]
          name= "PoC"
          parent = "video"
          weight = 43
          identifier = "poc"
          url = "/categories/poc/"
      [[menu.left]]
          name= "Point Sécu"
          parent = "video"
          weight = 43
          identifier = "point-secu"
          url = "https://www.youtube.com/channel/UCe-0FAoHZyDLPMLHnYAuXsw"
  [[menu.left]]
      name= "SecHebdos"
      pre = "fa-newspaper-o"
      weight = 50
      identifier = "sechebdo"
      url = "/sechebdo/"
  [[menu.footer]]
      name= "À propos"
      pre = "fa-info-circle"
      weight = 60
      identifier = "apropos"
      url = "/apropos/"
